### PR TITLE
Building using MXE on UB 18.04 fails without ws2_32 being linked.

### PR DESCRIPTION
**Pull request by ams-tschoening**
Error messages like the following occur:

    [ 26%] Linking CXX executable fwb_ipt.exe
    ../iptlib/libiptlib.a(PolicyCompiler_ipt.cpp.obj):PolicyCompiler_ipt.cpp:(.text+0x1a23): undefined reference to `_imp__ntohl@4'

Similar problems have been reported on other projects and the solution always was to link `ws2_32`, like in the following example:

https://github.com/kohler/lcdf-typetools/issues/22

Applying this PR makes things build on my UB 18.04. Note, though, that I'm not using Docker or else, but simply installed MXE manually and followed pretty much what you have done in the shell scripts for Docker and Travis regarding MXE. Shouldn't make a difference in my opinion, if at all the concrete version of MXE might make a difference. While you are explicitly using a specific commit, I was simply using the master cloned a week or two before.

You: 0567f17d34463abda1790957812c54e8c0cf59fe 

vs. 

Me:

    commit 951c528c4e75fca058f491f0894fdb389294b61c (HEAD -> master, origin/master, origin/HEAD)
    Author: MXEBot as Travis CI <mxebot@gmail.com>
    Date:   Wed Apr 22 09:45:36 2020 +0000

    Update packages.json & build-matrix.html

### CODE REVIEW

**Comment by ams-tschoening** [comment]
The failing test is the following:

    23: FAIL!  : instDialogCompileTest::testCompile() 'list->topLevelItem(i)->text(1).contains("Success")' returned FALSE. ()
    23:    Loc: [/fwbuilder/src/unit_tests/instDialogCompileTest/instDialogCompileTest.cpp(267)]

https://travis-ci.com/github/fwbuilder/fwbuilder/jobs/326251391#L2747

That doesn't seem to be related to my change, because the same test fails for [former builds](https://travis-ci.com/github/fwbuilder/fwbuilder/jobs/323119882#L2737) as well.

**Comment by sirius** [comment]
Thank you for contribution! While I use mxe in a Docker container, it should of course also be possible to use mxe packages for Debian/Ubuntu.

Don't mind the unit tests now - some of them are still a bit flaky. I'll fix that.
