### ISSUE TITLE
Build fail on Mac OS

### ISSUE THREAD

**Issue by Fridus** [fwbuilder/fwbuilder#18]
**OS**: MacOS Sierra 10.12.2
**Commit**: dcc919d

**Qt**: 5.7.0
```
brew install qt5
qmake --version
QMake version 3.0
Using Qt version 5.7.0 in /usr/local/Cellar/qt5/5.7.0/lib
```

**Build**:
```
PATH="$PATH:/usr/local/opt/qt5/bin"
./build_mac.sh
```

**Error**:
```
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:95:14: error: use of undeclared identifier 'Ops'
    typename Ops::Type _q_value;
             ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:95:19: error: expected a qualified name after 'typename'
    typename Ops::Type _q_value;
                  ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:95:23: error: expected ';' at end of declaration list
    typename Ops::Type _q_value;
                      ^
                      ;
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:99:44: error: use of undeclared identifier 'Ops'
    T load() const Q_DECL_NOTHROW { return Ops::load(_q_value); }
                                           ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:99:54: error: use of undeclared identifier '_q_value'
    T load() const Q_DECL_NOTHROW { return Ops::load(_q_value); }
                                                     ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:100:45: error: use of undeclared identifier 'Ops'
    void store(T newValue) Q_DECL_NOTHROW { Ops::store(_q_value, newValue); }
                                            ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:100:56: error: use of undeclared identifier '_q_value'
    void store(T newValue) Q_DECL_NOTHROW { Ops::store(_q_value, newValue); }
                                                       ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:102:51: error: use of undeclared identifier 'Ops'
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                  ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:102:68: error: use of undeclared identifier '_q_value'
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                                   ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:103:52: error: use of undeclared identifier 'Ops'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                   ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:103:70: error: use of undeclared identifier '_q_value'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                                     ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:107:86: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingNative() Q_DECL_NOTHROW { return Ops::isReferenceCountingNative(); }
                                                                                     ^
/usr/local/Cellar/qt5/5.7.0/lib/QtCore.framework/Headers/qbasicatomic.h:108:88: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingWaitFree() Q_DECL_NOTHROW { return Ops::isReferenceCountingWaitFree(); }
                                                                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[2]: *** [.obj/PIXCfgLexer.o] Error 1
make[1]: *** [sub-parsers-make_first-ordered] Error 2
make: *** [sub-src-make_first] Error 2
ls: /Users/florentdetry/Dev/fwbuilder/src/gui/*.app: No such file or directory
Cannot find GUI bundle. My best guess was in /Users/florentdetry/Dev/fwbuilder/src/gui/
```

**Tried**: 
```
export CXXFLAGS=-std=c++11
./build_mac.sh
```

**Error**:
```
In file included from IPRoute.cpp:31:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

In file included from InetAddrMask.cpp:31:
In file included from ../fwbuilder/InetAddrMask.h:51:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

In file included from Inet6AddrMask.cpp:33:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

In file included from InetAddr.cpp:31:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

3 errors generated.
make[4]: *** [.obj/InetAddrMask.o] Error 1
make[4]: *** Waiting for unfinished jobs....
3 errors generated.
make[4]: *** [.obj/Inet6AddrMask.o] Error 1
In file included from Address.cpp:33:
In file included from ../fwbuilder/Address.h:31:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

3 errors generated.
make[4]: *** [.obj/IPRoute.o] Error 1
3 errors generated.
make[4]: *** [.obj/Address.o] Error 1
3 errors generated.
make[4]: *** [.obj/InetAddr.o] Error 1
make[3]: *** [sub-fwbuilder-make_first-ordered] Error 2
make[2]: *** [sub-src-make_first] Error 2
make[1]: *** [sub-libfwbuilder-make_first-ordered] Error 2
make: *** [sub-src-make_first] Error 2
ls: /Users/florentdetry/Dev/fwbuilder/src/gui/*.app: No such file or directory
Cannot find GUI bundle. My best guess was in /Users/florentdetry/Dev/fwbuilder/src/gui/
```

This bug provide from an incompatibility with macOS 10.12 and xcode 8.
See my tests : https://travis-ci.org/Fridus/fwbuilder/builds/186353049  
And see this : https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

**Comment by Fridus** [comment]
**Tried**: 
```
export CXXFLAGS=-std=c++11
./build_mac.sh
```

**Error**:
```
In file included from IPRoute.cpp:31:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

In file included from InetAddrMask.cpp:31:
In file included from ../fwbuilder/InetAddrMask.h:51:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

In file included from Inet6AddrMask.cpp:33:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

In file included from InetAddr.cpp:31:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

3 errors generated.
make[4]: *** [.obj/InetAddrMask.o] Error 1
make[4]: *** Waiting for unfinished jobs....
3 errors generated.
make[4]: *** [.obj/Inet6AddrMask.o] Error 1
In file included from Address.cpp:33:
In file included from ../fwbuilder/Address.h:31:
In file included from ../fwbuilder/InetAddr.h:49:
../fwbuilder/uint128.h:469:29: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                            ^

../fwbuilder/uint128.h:469:40: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf, "%"PRIX64"%08"PRIX64, (uint64_t)hi,(uint64_t)lo);
                                       ^

../fwbuilder/uint128.h:471:28: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            sprintf(buf,"%"PRIX64,(uint64_t)lo);
                           ^

3 errors generated.
make[4]: *** [.obj/IPRoute.o] Error 1
3 errors generated.
make[4]: *** [.obj/Address.o] Error 1
3 errors generated.
make[4]: *** [.obj/InetAddr.o] Error 1
make[3]: *** [sub-fwbuilder-make_first-ordered] Error 2
make[2]: *** [sub-src-make_first] Error 2
make[1]: *** [sub-libfwbuilder-make_first-ordered] Error 2
make: *** [sub-src-make_first] Error 2
ls: /Users/florentdetry/Dev/fwbuilder/src/gui/*.app: No such file or directory
Cannot find GUI bundle. My best guess was in /Users/florentdetry/Dev/fwbuilder/src/gui/
```

**Comment by sirius** [comment]
I have updated the mkspec to macx-clang, and fixed the "invalid suffix on literal"-error. Please try again with 5.3.7. Beware of a buggy macdeployqt on Qt 5.7. This may result in the binaries getting linked to both the system and bundle version of the Qt libraries, and the application will segfault.

**Comment by Fridus** [comment]
Hi,
I try to build on commit 83665cb (v5.3.7)

```
export PATH=/usr/local/Cellar/qt@5.5/5.5.1/bin:$PATH
./build_mac.sh
```

Error :
```
Undefined symbols for architecture x86_64:
  "std::string::compare(std::string const&) const", referenced from:
      bool std::operator<<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libfwbcisco.a(InspectionClassMap.o)
      bool std::operator<<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libfwbcisco.a(inspectionProtocol.o)
  "std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::allocator<char>::allocator()", referenced from:
      InspectionClassMap::getIPProtocol() in libfwbcisco.a(InspectionClassMap.o)
      InspectionClassMap::getPrintableName() in libfwbcisco.a(InspectionClassMap.o)
      ___cxx_global_var_init.1 in libfwbcisco.a(inspectionProtocol.o)
  "std::allocator<char>::~allocator()", referenced from:
      InspectionClassMap::getIPProtocol() in libfwbcisco.a(InspectionClassMap.o)
      InspectionClassMap::getPrintableName() in libfwbcisco.a(InspectionClassMap.o)
      ___cxx_global_var_init.1 in libfwbcisco.a(inspectionProtocol.o)
  "std::ostream::operator<<(std::ostream& (*)(std::ostream&))", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::ostream::operator<<(int)", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:
      InspectionClassMap::getIPProtocol() in libfwbcisco.a(InspectionClassMap.o)
      InspectionClassMap::getPrintableName() in libfwbcisco.a(InspectionClassMap.o)
      ___cxx_global_var_init.1 in libfwbcisco.a(inspectionProtocol.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:
      InspectionClassMap::getIPProtocol() in libfwbcisco.a(InspectionClassMap.o)
      InspectionClassMap::getPrintableName() in libfwbcisco.a(InspectionClassMap.o)
      std::pair<std::string const, InspectionProtocol*>::pair(std::pair<std::string const, InspectionProtocol*> const&) in libfwbcisco.a(InspectionClassMap.o)
      std::pair<std::string const, InspectionProtocol*>::pair(std::string const&, InspectionProtocol* const&) in libfwbcisco.a(InspectionClassMap.o)
      std::pair<std::string const, InspectionProtocol*>::pair(std::pair<std::string const, InspectionProtocol*> const&) in libfwbcisco.a(inspectionProtocol.o)
      std::pair<std::string const, InspectionProtocol*>::pair(std::string const&, InspectionProtocol* const&) in libfwbcisco.a(inspectionProtocol.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()", referenced from:
      InspectionProtocol::InspectionProtocol(std::string const&, std::string const&, std::string const&, int, int) in libfwbcisco.a(inspectionProtocol.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
      std::pair<std::string const, InspectionProtocol*>::~pair() in libfwbcisco.a(InspectionClassMap.o)
      std::pair<std::string const, InspectionProtocol*>::~pair() in libfwbcisco.a(inspectionProtocol.o)
      InspectionProtocol::InspectionProtocol(std::string const&, std::string const&, std::string const&, int, int) in libfwbcisco.a(inspectionProtocol.o)
      InspectionProtocol::~InspectionProtocol() in libfwbcisco.a(inspectionProtocol.o)
      ___cxx_global_var_init.1 in libfwbcisco.a(inspectionProtocol.o)
  "std::string::operator=(std::string const&)", referenced from:
      InspectionProtocol::InspectionProtocol(std::string const&, std::string const&, std::string const&, int, int) in libfwbcisco.a(inspectionProtocol.o)
  "std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::_Rb_tree_decrement(std::_Rb_tree_node_base*)", referenced from:
      std::_Rb_tree_iterator<std::pair<std::string const, InspectionProtocol*> >::operator--() in libfwbcisco.a(InspectionClassMap.o)
      std::_Rb_tree_iterator<std::pair<std::string const, InspectionProtocol*> >::operator--() in libfwbcisco.a(inspectionProtocol.o)
  "std::_Rb_tree_increment(std::_Rb_tree_node_base*)", referenced from:
      std::_Rb_tree_iterator<std::pair<std::string const, InspectionProtocol*> >::operator++() in libfwbcisco.a(InspectionClassMap.o)
      std::_Rb_tree_iterator<std::pair<std::string const, InspectionProtocol*> >::operator++() in libfwbcisco.a(inspectionProtocol.o)
  "std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)", referenced from:
      std::_Rb_tree<std::string, std::pair<std::string const, InspectionProtocol*>, std::_Select1st<std::pair<std::string const, InspectionProtocol*> >, std::less<std::string>, std::allocator<std::pair<std::string const, InspectionProtocol*> > >::_M_insert(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::pair<std::string const, InspectionProtocol*> const&) in libfwbcisco.a(InspectionClassMap.o)
      std::_Rb_tree<std::string, std::pair<std::string const, InspectionProtocol*>, std::_Select1st<std::pair<std::string const, InspectionProtocol*> >, std::less<std::string>, std::allocator<std::pair<std::string const, InspectionProtocol*> > >::_M_insert(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::pair<std::string const, InspectionProtocol*> const&) in libfwbcisco.a(inspectionProtocol.o)
  "std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      InspectionClassMap::getMatchCommand() in libfwbcisco.a(InspectionClassMap.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [fwb_pix.app/Contents/MacOS/fwb_pix] Error 1
make[1]: *** [sub-pix-make_first-ordered] Error 2
make: *** [sub-src-make_first] Error 2
==> Copying base bundle
==> Copying resources and libraries into bundle
==> Copying binaries into bundle
cp: /Users/xxxxx/Dev/fwbuilder/src/pix/fwb_pix.app/Contents/MacOS/fwb_pix: No such file or directory
==> Stripping binaries
==> Running macdeployqt
ERROR: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'fwbuilder.app/Contents/MacOS/fwb_pix': No such file or directory.\nfatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed\n"
ERROR: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'fwbuilder.app/Contents/MacOS/fwb_pix': No such file or directory.\nfatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed\n"
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: fwbuilder.app/Contents/MacOS/fwb_pix (No such file or directory)\n"
ERROR: ""
ERROR: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'fwbuilder.app/Contents/MacOS/fwb_pix': No such file or directory.\nfatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed\n"
==> Done
# open fwbuilder.app/
```

And `src/pix/fwb_pix.app/Contents/MacOS` is empty
